name: test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "EVENT=${{ github.event_name }}"
      - run: date
